const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  enabled: { type: Boolean, default: true },
  approved: { type: Boolean, default: false },
  registrationComplete: { type: Boolean, default: false },
  initialQuestionnaireSubmitted: { type: Boolean, default: false },
  emailVerified: { type: Boolean, default: false },
  emailVerificationExpires: { type: Date },
  emailVerificationToken: { type: String },
  resetPasswordToken: { type: String },
  resetPasswordExpires: { type: Date },
  subscribeNewsletterToken: { type: String },
  subscribeNewsletterExpires: { type: Date },
  unsubscribeNewsletterToken: { type: String },
  language: { type: String, default: 'en' },
  gender: { type: String },
  firstName: { type: String },
  lastName: { type: String },
  birthday: { type: Date },
  phonenumber: { type: String },
  address: { type: String },
  housenumber: { type: String },
  postalCode: { type: String },
  city: { type: String },
  country: { type: String },
  role: { type: String, enum: ['Admin', 'Practice', 'Therapist', 'Patient'], default: 'Patient' },
  refreshToken: { type: String },
  refreshTokenExpires: { type: Date },
  lastRefreshTokenAt: { type: Date },
  createdAt: { type: Date, default: Date.now },
  lastLogin: { type: Date, default: null },
  loginCount: { type: Number, default: 0 },
  newsletterSubscribed: { type: Boolean, default: false },
  eulaAccepted: { type: Boolean, default: false },
});

module.exports = mongoose.model('User', userSchema);